feat: New Aircraft Updates tab
Pinpoint-Simulations/website pull request #2
Opened 2021-04-27 22:49 UTC by Spherrrical

New aircraft updates tab in the website (Work In Progress for Automation)

2021-04-27 23:54 UTC, scoopscode requested changes

2021-04-27 23:54 UTC, scoopscode commented on aircraft.html
> +    <h1 class="title">AIRCRAFT UPDATES</h1>
Change "AIRCRAFT UPDATES" to "UPDATES" for all progress from our projects.

2021-04-27 23:54 UTC, scoopscode commented on aircraft.html
> +    <footer class="copy"> ©️ Pinpoint Simulations 2021</footer>
Remove copyright (unless we are copyrighted in which I didnt know).

2021-04-27 23:54 UTC, scoopscode commented on index.html
> +      <a class="navbarlink" href="aircraft.html">AIRCRAFT UPDATES</a>
Same from above, change to "UPDATES"

2021-04-27 23:54 UTC, scoopscode commented on privacy.html
> +      <a class="navbarlink" href="aircraft.html">AIRCRAFT UPDATES</a>
Same as above, change to "UPDATES"

2021-04-27 23:54 UTC, scoopscode commented on pull_requests.html
> +      <a class="navbarlink" href="aircraft.html">AIRCRAFT UPDATES</a>
Same as above, change to "UPDATES"

2021-04-27 23:54 UTC, scoopscode commented on tos.html
> +      <a class="navbarlink" href="aircraft.html">AIRCRAFT UPDATES</a>
Same as above, change to "UPDATES"

2021-04-27 23:56 UTC, Spherrrical commented on aircraft.html
> +    <footer class="copy"> ©️ Pinpoint Simulations 2021</footer>
We are allowed copyright under the GPLv3 License. You can check description for their copyright notice.

2021-04-27 23:59 UTC, Spherrrical commented
Everything has been changed to current

2021-04-28 00:03 UTC, scoopscode approved these changes

2021-04-28 00:04 UTC, merged