Added Branding Page
Pinpoint-Simulations/website pull request #5
Opened 2021-05-31 11:08 UTC by AnAussiePilot

Added HTML & CSS to Brandng

2021-05-31 11:50 UTC, scoopscode commented
What is your Discord? (If you are in our Discord server)

2021-05-31 17:45 UTC, Megabrains44 commented
Looks good, maybe I'll add some of the previous styling on the other pages to branding.html

2021-05-31 21:19 UTC, AnAussiePilot commented
mad

2021-05-31 23:15 UTC, scoopscode requested changes

2021-05-31 23:15 UTC, scoopscode commented on Branding.html
> +      <p>If you would like to use our logo or images, and provide credit, you must follow the following conditions</p>
When I preview the site, all the text seems a bit off center. Making a new info class with different centering may work or you can modify this info class.
![image](https://user-images.githubusercontent.com/71532026/120248091-68ad9f00-c23b-11eb-9ea5-57a32a71fdc5.png)

2021-05-31 23:15 UTC, scoopscode commented on Branding.html
> +      <p>Find Logo in Transparent and Black Background Format at the Following Link : <a href="https://github.com/Pinpoint-Simulations/branding" >https://github.com/Pinpoint-Simulations/branding </a>
```suggestion
      <p>Need help finding the logos? Follow this<a href="https://github.com/Pinpoint-Simulations/branding" target="_blank">link.</a></p>
```

2021-06-01 00:06 UTC, AnAussiePilot commented on Branding.html
> +      <p>If you would like to use our logo or images, and provide credit, you must follow the following conditions</p>
Aight. Will do

2021-06-01 07:12 UTC, Spherrrical commented
How were you able to preview the site? I would like to see for myself then request any needed changes.

2021-06-01 08:24 UTC, AnAussiePilot commented
Download the Files and run them in your browser

2021-06-01 21:27 UTC, Spherrrical commented
Try to add CSS to the link to make it white and not blue. I'll download the files and see what I can do with it.

2021-06-17 08:26 UTC, scoopscode commented
Can we get an update on this?

2021-06-22 04:58 UTC, scoopscode commented
Closing due to inactivity

2021-06-22 04:58 UTC, closed without merging